services:
  userDao:
    class: IpepsWapi\UserBundle\Dao
    public: true
#    ipeps_wapi_user.example:
#        class: IpepsWapi\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
