ipeps_wapi_doctrine_test:
    resource: "@IpepsWapiDoctrineTestBundle/Controller/"
    type:     annotation
    prefix:   /

ipeps_wapi_user:
    resource: "@IpepsWapiUserBundle/Controller/"
    type:     annotation
    prefix:   /

ipeps_wapidemo:
    resource: "@IpepsWapiDemoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
