<?php

namespace IpepsWapi\DoctrineTestBundle\Repository;

/**
 * table3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class table3Repository extends \Doctrine\ORM\EntityRepository
{
}
